# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c54729e0bc18f990101b85cb777f7c9"
name = "Artwear Design"
handle = "artwear-design"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false


[access_scopes]
scopes = "read_customers,write_customers,read_customer_metafields,write_customer_metafields"
